### ISSUE TITLE
Training Time Slower Than Reported on 4×A100 GPUs for Action Model

### ISSUE THREAD

**Issue by wanghonghui1998** [roboterax/video-prediction-policy#5]
Hi there,

Thank you for open-sourcing your great work.

I’ve attempted to train the action model on CALVIN ABC following the provided instructions:
`accelerate launch step2_train_action_calvin.py --root_data_dir ${path to Calvin dataset} --video_model_path ${path to video model} --text_encoder_path ${path to clip}`

I used the default configuration with 4 A100-40GB GPUs, a global batch size of 28, and a maximum of 50 epochs.

During training, I observed an average speed of 0.42 training steps per second with nearly 100% GPU utilization. Given the dataset size of 696,473 and the batch size of 28, this results in approximately 59,223 seconds (or 16.5 hours) per epoch.

However, the paper mentions that this stage should take only about 6–12 hours on 4 NVIDIA A100 GPUs. Could you clarify if there are additional optimizations or settings that might explain this discrepancy?

Thanks for your help!

**Comment by Hu-Yuch** [comment]
Thank you for your attention to our work. We used 80GB of video memory a100 in our experiment, and the batchsize of a single graphics card was 32 (global batchsize 128). This may lead to faster training. And you only need to wait for eval_mse to drop to around 0.06, without waiting for 50 training stages.

**Comment by wanghonghui1998** [comment]
Thanks for your quick reply.

It turns out I was not using the correct Accelerate configuration. With the proper setup, the global batch size is now 112 on 4 A100-40G, and I’m observing an average speed of 0.42 training steps per second, which translates to approximately 4 hours per epoch.

Could you kindly share how many epochs are typically required to reach an eval_mse of around 0.06?
